"use strict";

function hmmm () {
  console.log("hmmm i wonder what would happen if you typed 'whitley()' right now?");
}
hmmm();

window.whitley = function () {
  console.log("Are you ready to meet the second greatest country singer of all time?");
  setTimeout(function() {console.log("He's no stranger to the rain, ladies and gentlemen, introducing...");}, 2000);
  setTimeout(function() {console.log("KEITH WHITLEY!");}, 4000);
  setTimeout(function() {console.log("ps. Better open those dev tools all the way up");}, 6000);

  setTimeout(function(){
    console.log("mNNmmmNNNNNNNNNNmmNNNNNNmNNNmmmNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy");
    console.log("mNNmmmmmNNNNNNNNNNNNNNNNmNNmmmmNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy");
    console.log("mmmmmmmmNNNNNNNNmmNmNNmNNNNNNNNNNNNNNNNNNNNNNNNNmNmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy");
    console.log("mmmmmmmmmmmNmNNmmmmmmmmmNmmNNNNNNNNNNNNNNNNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMy");
    console.log("mmmmmmmmmmmmNNNNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy");
    console.log("mmmmmmmmmmNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy");
    console.log("mmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmmmmNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMNMMNNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNmmdmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("NNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmmdddddddddmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("NNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMNNNNNNNmmmmmmmmmddmmdddddhhhdmNNNNmNNNNNMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("NNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMNNNNNNNNmmNNmmdddmmmddmmmmmmmdmdmmdmmmmddmdhhhhyyyyhhdmNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("NNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmdmmhyyhhddhdddhhhdhhhddddddddmmmmmdhhhddmmmddhdddmmmmmmNNNmdhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNmdddhdhhddysyhyshhhhyo+oyyhhhhhhyhhddmdddhhhdmmdddhhhyyyhhhhyyydmNNNmmdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdmddddhyysyhhhyyso+syssys+osysyhhhhhyyhddmdhyhhhhhhhyyysssyyhhyyysssydmNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyddhyhhssyyhhhoos+osooyhhhys+oossyhhhhsyhddhhyyyhysyyssyssyyyhdhyysssooydmNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddmhydhyyhyssydhysssossy+ymmddhyhhyyyyhhysooyhdhdddddhhhysyyyhsoyhdddhysssssyhmmNNNmNmmNNNNNNNNNNNmmNNNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhdhydyyhhyyyhhhhhysohysoddmmddmdysshdmdhyyhyhhddddhhhhhhyhdmddhhdddddhdhyyyyyhddmNNNNNNNNNNNNNNNNNNNNNNNNNNNMd");
    console.log("MMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmddhhyshysyysyhhhhyysooyhyhdmNmNmhysyhdmmmmmmmmmmmmmmmdddhyyyhdddmmmdhddmmddhhsooyyhdmmNNNNNNNNNNNNNNNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmddhdhhysyyooyyyhhhyysyssyhhhhmmmmmhyyhhmmmmmmmddddddddhyyyso+oshddmmmdhdmmdmmddysssyhhhdmNNNNNmmNNNNNmNNmNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmdyyydhhdysyhysyyyyysyhddhydmdhmmNmmmmddmmNNNNmmmmmmmdhhhyyhhyyyyhhdddddddmmdddhdhyyyhdddddmNNNNmNNNNNNNNNNNNNNNNmNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmdmhhyyhhhhdmdhhhhyyyssyhddmddmmNmmmNmmNNmNNNNNNNmNNNNmdhdNNmmmmddddddddddmdddhdhhhddhso+oyhhhhmmNNNNNNNNNNNNNNNNNNNNNy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmdddyhhsyyyhdmmdhhdhysoshdmmmmNNNNNdmNNNNNNNNNNNNNNNmmmmNmdmmmmmddysosysyhhhdhdhddhdmmdys+/+sosyydmNNNNNNMMMMMMMMMMMMMMd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyhdhyyyyyhhhyhyhyhhdys+odNNmmNNMNNNNmNNNNNNMMNNNMNNmmmmmNNdyddhyyyhddhyhmddmmddhyhddhdddhso+osyhydmNmmmmmMMMMMMMMMMMMMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMmhdhyhhyyyyyhhyyysshyysyds++ymNNNNNNNNMNNNNMMMNMNNNNNNmmdmmhhddhhsossoyhhhyyyhhhdhhhdhddmddhyyoooyhhhddddmdhdmNMMMMMMMMMMMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMNyhhdddhohhysyysssyyyhdy+yhyssdmNNNNNMNMNNNNMMMNMNNNNNNNmNmdhhhyyo+/yyyyyyssso+oyhdmmmddmmdydyhdhysydmmdhddddmdmNMMMMMMMMMMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMdyddmmdhosyyssssysso+shdhsddhhhhhhhdmNMMMMNNMMMNNNNNmmNMMNNmdhs+o+:-odhhhhhysoosyhddmNNNmmhyddhyhyyysydmhddddmmmmNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMNNhdddhyhs+osooosyyssosydmmdddyssyhddhmNMMMMMMMMMMNNmmNNNNNmdhyso/ooosyhddmdmmmmmdhhmmNNNNdydddmdhhddhyhdhdmddddmhddmmmmmmmmmh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMNNmddhssssso+osossyssooohmmNdoyNNNmNNNNNMMMMNNNNNMMNNNNNmhyysssooso++syhdmmNmmNmmmmhdhhmmhyhhhhhyhyhddhhyhhdddhddhyhdmddmmmmdy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNdmmmhhysysssssosyysssddysoyyo/mNNNNNNNNNNNNNNNNNNNNNNNNmhddhhhhyyyyooooyhddhhdmdddmdhhooyhhysyhhysyyssssshyyyhhhdmhhhddddddddy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNddmhhyhhysoyhddddddddhyyhyysosmmmNNNmNNNmdhdmdddmmNNNNmmmmNNNmddmdyosyyyhhhhyyhhhddhsosyyysysyyhyssso+ooyyyyhhdddmmmdddddddddy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNNdddddddhyyooyhdmmdhhhhyyshddhhmmmNNNmmmhyyyhhddmmNNNmmNNNNNNNNmmmdhoysyhhhhhhdyyyhysssoyyssyhyyyhyyhysooyssohhdddmmmmhyhddddds");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNddddhhhhhyyyyyhhhyyyyhhsssydmddhddmmdhdoysyssshhdmmmmmdhhdhyyhhdddmhsdyossyysyhhyhhhyssso+++oyhhdyyyysooshyo+yyhhdmmmmmyhddddds");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNdhddhhhhhyyyyyyysyhhhds++syhdmmddmmds++/oyso++syddddyo+ossssyhhhyhddydmhssssso+ssyyssooo++ooosyssyyys+++yssoosyyshddmmmdhhddhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNyhdhyhhysssssyysyhhos////syddddhdh+/://os+:/+ssyhs++//+++ss+syyssyhhyoyysso++++++ooossooo+++o+oooo++ooooooooosysydmmNmddhddhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNNdyyhyyhhhsoso+osssoos+///syhdmmh+:::+o+os+++oosss++oosso+yo+yso+oshy++sys+/ooo+oooo+++///++/++/++/:/o++++syo///hmmNNNmdddddhds");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNNdhhyyyyyysso+ossso+/+soo+oyyhdd+.:/:+sysssoooossoosyhhyooy++sso:/oys/osso//o+++o++oo+//://:-:/++s+/://+oosys++:ymNNNNNNNmddhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNNmdhhyshyssosyyhyso+/oyyhossdmds/:oo/ssyyyyysosyy+syhhhhyss++oos+oooo/+oso+///:++//++///--:++/+syho++:/oyoyysso+sdmmNNNNNNdddds");
    console.log("MMMMMMMMMMMMMMMMMMMMNmmNmmmhsyhhhyyyhhhyssyyhhddhhhhddh+sysyysyyyyyssysyossyyhyysso++osss++o++++oo+/:://:-::--/++++ooosyy/+s//++shyysoosyydNNNmmmdhdds");
    console.log("MMMMMMMMMMMMMMMMMMMNdmmmmmmdyhhdhhysoosssyyyhhdddhddmmhshyhhyyyyys+////osssyysssso:/++oo+//////:://:::://:://++++oosssss//+/:::/oyyssssyyoydNNNdmdhdhs");
    console.log("MMMMMMMMMMMMMMMMMMMmhdddddyhyhhddhyys++oyysyysyyyyhdmddddddysoo+++:..-:/ossoo+///:--:--::::::::::::::://////+oosoooooyo+++++//:+ossssyyyyyyydNmhddddhs");
    console.log("MMMMMMMMMMMMMMMMMMNmhhhdmmdhyyyydhssoosysso+//+oo++yhhhdddh+::+ooo:...-://+/:--....`...-----::/::/+++///+/+++oosso+++oosoo+/////+osyyyyyyyyyymmdmhhhds");
    console.log("MMMMMMMMMMMMMMMMMMNmdhddhyhdhhdddmyssyyss+++///::::///syhys+-:///+//:-..----....``````.....--::///+oso+//++/+osyysoo+////+//+++/+syyhyyysyyyyhmmmdhhhs");
    console.log("MMMMMMMMMMMMMMMMMMNmdhssyhhhhhmNNNdyyyyso+////::------:/oo+/:--://++/:-.--.```.-..````.---...-:+++/+++/:/++o++ososo++:-:://::---/oyyhhyyoosyhddmmdyyhs");
    console.log("MMMMMMMMMMMMMMMMMMNmmmy/+yhmmddmNMNmdhsso//:::------.---:---..-::::::--..``  `.---````.-----.-:://::-::::++oo+osso+////+////:/:/+shdmdhhysosyyhhmhyyhs");
    console.log("MMMMMMMMMMMMMMMMMMNddmhoydmmddyhNMNmhsoo+/::-------.............-----...``` ` ``..````..----.-----:-::/:/++++ooss+s+::/oooo/++/:/ydmmddyyyosyshhddhhhs");
    console.log("MMMMMMMMMMMMMMMMMMNmNdyydmddmmddNMNdsoo+//:::-----................`.```````     `.`````...--::-..----://///+++oosooo/+/oss//++oosshdddddyyssshhdyddyys");
    console.log("MMMMMMMMMMMMMMMMMMMNNdhdmdydmNNMMNNmhsoo++/::::---.......``.....`````          ```.`.``...---.-.---::///::/++ooo+++o/+oyys+:-:+sssydmmmmdhyyoyhhdyysys");
    console.log("MMMMMMMMMMMMMMMMMMMMNmdmmdhddNMMMNNNmdhyyys+///::---.....`.....````            ``````......-....---:::///:/++ooy//++ooyyhyoo+/+ssysdmmmdddhyyyyysosshs");
    console.log("MMMMMMMMMMMMMMMMMMMMNNmmNdhdmNMMMMNmhhdddddhysoso/:-.........```````           ``````............-----:////:++ys+://+osyhys++ohhsyyyyhmdmdhhdhddosoyhs");
    console.log("MMMMMMMMMMMMMMMMMMMMNNNmmdhdmNNMMMNmhssooossyyhhhhs/:-...----...--:--...`````````................-.-::::/:/-+syyo///+++syyo/oosyyyhhysyhhhddddmddhhhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMNNmmmmdmNNNMMMNmmmmdmNNNmy++yhhs/:------/-.-+ssyyo+o+/::::::----...........------://::--+ssss++//+ooos///::+syhhssshdmdhyyydmhhhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMNmmmmmmmNNNNMMmmmdhymmNMds..-:+ys/-----::--:++osyhdhhhsooso////::---..----------::////:-/ooyy+:::/+oo+/::-:/ohhs+ossshssssydmdhhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMNmmmNNmddmddNNhhdyo+ohmdo.  .:.:so--.`...--:-::::/++oo+/://++++//:--------:-----:://+++:/ooyyy:-/ossyyso+//sdho+o++o+shysyhhmmdhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMNmmmNNmdddNMmsshyo+++/:-`..::-.+s-.````....---::/+ssdmhs/.``.--::::::::--------:///+/++//+shys+/-:+ss+++soshdyosooysososhhmNmhhhy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNNNmmmdmNMNyo+yys//:::::--...:so-.```..-...``..:/.omNMmmh++::------:::---:-:-::::///+ooo/oyhhso++oosso+sshmmdyo+/////osdhdmmhhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMNs++osso+//:::::--/oy/..```.-...```.-:/--sdmds.`:oo::--------::-::--:://:+ossyhhhdhy++++osysso+yddhooyooosyhmddhyhhhhs");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNmmmmddNMMmo+//+oo+++///:::/+y+-.``...-..````-:::::-/:-```.:/:-----...---------://:/osyyyhddhyo+oyyhhys+ohddh/ohhhddddddhydhhhhy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNNmmdddNMNdo+//////////:::/+ys:-.`...---.````-:/::-..``  ```.....-.......------:////oyhhysyyhysoyyddmdysoydmhsymmdmddysdmdmmmmmh");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNmmdhhmNMNho+////:::::::::+sy/-.`...---..`````.-:---.````````.....`````...----:::/+ssyhhdhyyssysydmdmysooyhddhdmdmdmdyydmdmmNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMNdhdhdmNNMNyo+//::-:::/::/+syo-.`...---...`  ````.---...``````...`````....----::::/oshhhddhs++shyshdddhsooshhhhdhhdyhdddddhdmNMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMMMmdyyhdNMMNho++/:::::/:::+sso:.``.........`````````.......`.`````````...---::::::/+soshddhs+::+sooyhdddhhhyhyss++ssshhdmdyydNMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNNNmmmNMMNds++/:::::::/osyo/-.``..-....``````````````..``..`````````..-:-:::::/:/+sssyydy/:-:/-.-+ssydddhyyyyyyyshddyhmmdhdNMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMNhs+/::::///osss/:-```..---....`.-..`````````````` ``````..--:::::///:/ossyhys+/--/+/::/:ohdhyssyoyyhhdhyshddmmhmMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMmy+////:::+hsso/:-```.-----------::-.``  ``       ````....---://///:/+syyssho:..:-...--/sdyshhhhhyhddhsoohddhhdmMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMNNNmNNMMMmds+//////odhs+::.` .----------:/:-::-.````       ```..-----:://////osyyosyy+:---````.-:ohhhhdddhyhdddhyyyhhyshmMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMmdy+////+oshmy//:. `.-------::::.``.-//-..``     ``...------:://///:osssyydho---.````.--/hddddddmmmddddhhhhhhhhmMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMNNmNMMMNNdd+/oossyhdmmy+/:--::/://///:-.``....:+/-..`````...-------:-:////++shyyhhdyy:.-.``..-:oydmmddmdmmmNmmdddhmdhhdmMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMNmNNMNNNddssyhhyhhddhhhsoo++ssssoss+/::/:--.`.:+/:-......-----:::--::/+//oooydyddhsdy::---:+oydmmdhhdmmNNmdhdddhhhyhdNNMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMNNmdhhhddddddddddhyys+yddhhhhysosyo//--..-/+/:-------::-:::-:::/++ssyyhddmdhydNdhyyhdNNNNNNddyydmmmhyydhddyyhddmNNNNNN");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMNmddhss+ooydmmmmmds+:sddddhdhsyhhyss++/::-:+:---:::///:::::-+//oyydhddddmdhhmNNNNMMMMNmNmmdhyyhdddssshhhdmmmdhdmmmNmd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMNmmhs+:::-oyddy////::+yyhhhyssyhysssooooo/://---:////:::::::/++ohdhddhdmmdhmNNNNMMMNmyyddmmdhhdmmddhhdhddddmddddmdddh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMNNNdyo+:-:syhhhs:`   ````.-``-::/osssosysss/:---::/+:::+////+ooohmhdmmNNNmddmmNMMMNNmdhsydmdhddmmmmhddhhyhhdddddhdddy");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdho+//shyysss/-.`.    ```.--:ossooyyyhso:.-::/++///+sssossyydmmmNNNNNmdmmNNMMNNmyso//syyydmNmddyhdhhhhhhyhdhydddh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhs++oysso+++++/+/:-:/++o++++:-..:oyyys/-:/+oo+ooo+sdhhhyhdmmmNNNNNNmmNNNNMMNNNmhyo+ooyhdNNNmdhyyyyhhhdhhhyyhmmh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMNmdyo++ssoo++++/////:::---........./osyo/-/oosssssssyydhddydmmNNNNMNmdNmNNNNMNNNNNmyooyydddmmmmmddhyyddhmdddddmNm");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMdmNMMMMMMMNmdhso+ossoosyso////:-............./++ooo+osssyyyysyyshdmmmmmmNMMNNmmmNNMMNNNNNhhddyo+shdhdNddmmmdddddddmdhdmdmNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMNNNmddNNMMMMMNNdhhyo+syyyddyysssoo/::::---....--//oosysshyhhysyydddmdNNNNNNMMNNddmNNMNNmmmNNNy+syyhhhhshdddhyydddddhhyyohhhhdh");
    console.log("MMMMMMMMMMMMMMMMMNNNNmmdhhhdddmMMMMMMMNmddhs++syyhdhhdhhsyyo+/:--..----:ooyhhhdddhdhshdhmmNNNNNNNMMMNmhhdmNNNNdddhdmmmyosyhhhhyhyhhddhhdhddhhhyyyys+sy");
    console.log("MMMMMMMMMNNNmmddhhhyyssoooss+oyNMMMMMMNNmdhyo:ossyydddhhyssso/:------/+oyyhddmmmmdddmmmNNNNNMNMMMMMNhyysyhmmmmdyhhddmddhsyhhdhyyyhhhddddhyhdhys+ossssy");
    console.log("MMMMMMNmhysssyyyyyoss+os//s//yydNMMMMMNNNmmdhoooyyyyhhysy+//::----:://oshdddmmNNNNNNNNNMMMMMMMMMNNmyhhyhhyhdmhsyyyyddddmdddddhhhhyyyhhddhyyso++//++o//");
    console.log("MMMNmdsssssoososys+so:+o::/:/+:+dMMMMMNNNNmmmdhhyyyhhyyyo/---:::/o/ssyhhddmmNNNMMMMMMMMMMMMMNNNmhsooysyyssyyhdssyymmNNmmNmmdhhhhhhhdddhdysyhys+//:::/-");
    console.log("Nmdyoo+osssoososyo/:-::----:-:+oyNMMMMMNNNNNmmmdyyyyyyso+://+sooshhhdddmmmNNMMMMMMMMMMMMMNNmdhs++++oyhysyhyhyssoymNNNNNNmmmdhysyyyddmmmdhhhh+/+o+::-.-");
    console.log("yoy+/o-/yhsoosoo/:..---..::---/+ohNMMMMMMMNNmmmdhhhhyyss/soydyssdmmmdmmmNNNNMMMMMMMMMMMNNdso++++++ooyhhhdhyyso+ymmmddmNNNNmmhyyhdddmmmNmdmmy/++o++/:::");
    console.log("o/:///-/o+//++++-.-.`-:+/--:///++sdNMMMMMMNNNmmmdhddddyhyhdmddddmmmNNNNNNMMMMMMMMMMMNmhoo+/++/++oossoydmmdhssyyhs+sdNmmmmNmdmmmmmmmddmmmmdyo/:////++//");
    console.log(":::+//++//:/ooo:.-----//////++o+++oyNMMMMMMMMNNmdhmmmddhdmmmmmdmmmNNNMNMMMMMMMMNNmmhso+/++++++o+oosoyy++yyhdddhhshmmddddmhydddhdddhsyhdhso+/+//++//:::");
    console.log("//++::+//::/+++..---..-/+++//+o/:/oshdmMMMMMMMNNNNNNNmmmmmmNNNNNNNMNMMMMMMMMmdhhy++++++++++oooossosso/:+ssymhyyoydddy+oyhyoyyyhhhyyyyyh++o+///////////");
    console.log("-:/:.--:/::///:..-..-.-++/:--/+/+oo++syhmmNNMMMNMMNNNNNNNNNNMMMMMMMMNNNmddyso+++o++++++++ooosyoooso+/:/ss+oshs/oddddhhddyoosss+/o//+syh+:/-:.:-:--:://");
    console.log("-::--.-:///+++:--...``-:////:///+oo+//+osossydmNNMMMNNNNMMMNNmmmmddysysosoo++++++++++++++osys+oy+-.::+ss//+/://odho+syyssos+o+-/+:/oyyo::--+:://:..///");
    console.log("`----.:://///:---...`..-++::///ooooo++++++:-:+ydmmmdddmmmmmmdhyoooo+o++++++++++o++++o+oosssss+o+.`.-/oos+:::-.--//-.-so/://.:--://oho+:--.---o+::+++o/");
    console.log("..-::::::///:..`....`..-+/:/+++sso+++++///--/ossydhhhhyydhhdmdhsooo+oooooooooo+ooooooo++++oso+/:---+so-.:::.``.:/::-/o:::-..-:////ss-.-+/:.-/+:-os/:o/");
    console.log(".--:--::///:--.----.`.://:-:++osyyo+o/://:-/osssshysyyhyyhhhddmdhysssssssooooo+oooss+///++o+/--::/oo://::```.--:/:::+-:--.---::-:/o:-`.::---::/o+++s+:");
    console.log("-:------/::---.--::---:+/:-/++oshyso++++/-:/+syyhyyshysyoshhhdddddhhyyyssosoosssoooo++++/::--..:+o+-..::-.`.::-/--:/:-:...-/-::-/s+:.`.::--://oo//oy+s");
    console.log(".-:--.-:-----.--.---:--++:-//+oosso///++:://oyyhysssyhhhy+osyhddhhhhhyyssssyyhyo++++///:-..----:/-.-:/:-.`.:----..//:/:...-//:::o+/:``-/:-.-:/+++ss+o+");
    console.log(".::---::::----------:-/o//:/+/ooooo+/://:/++oyyyysosysooyhssosyysooooshyyhhyo+/:://:--::/:-/:-.-//+/:+:-`-::--...:o///:-.--:://+o.--.-/:--.-:://:+oos/");
    console.log("--------:-.:/:-----..-/++/:+//++o++/://+/:/+os/ossosyhso+syhh+os+:::-/oyyso/:::::::/:--:///:....-+o+/-:--/-:::--:o/:/-...-/:/:/s:.-..:+:-...--:/+//++:");
    console.log("-----::-.--///::---:--/++//+/::/o++//++/:-/oo+/+syyyssyo:+dmNmy+::-```-omo--:--`./++/++/-......-://++:.//--:/--:+:.--..-:/:-::o+...`.:+::....-:+/:::--");
    console.log("-::-.::--:/+///:---:-:+o//++:://+/:/++o+///+o//osssyoo/++:shhyo+/+o/:+dms++:-:...+so::-.``...-:/-:/::.-+-/:-..-//-::-...-/----o-`.``./o-....-:/+-.-..-");
    console.log("---..---:////:-----.-:++//+/--::///+++o+++/+:+soho/o//:+o//oo+/oooso//+s+o+o:`.-/::++:--::-:+//o--.-.-:-:/-..-+/:::.``...:---+/..``.-/o:-...-:--:.`..:");
    console.log("://-.---:+++/::::---:/oo//+/--://++ooo+oo/++-+o/o+/oo+//o-oysoyo/oy+:s--o+-/::----+://`./:-:+o+/++:`.::-::--:/:-:-.`....-:--:o....-/+yo::-:/+--:-..:/-");
    console.log("/+/-....:+++::::/:://+o+/+o/--:/:+oso+os+::/--:/+osyo::+-shmyyoysshs/so./o/:-.-/-::/:-.-/+/-./+/.-..-:::.---//-:/:-.----//-:o/.-..:/oho:::+s+--..:+//-");
    console.log("+++-..-::/+/:::://::/oso/:::--::/++o+sd/:::/+/+++oso/--+:mddomh//sso++y.`//+/+:--o:./::::os-`:++:-.:::--..-:++:-:-..--:/:--+s-...-:/oy/::+oo//:-/+o+/:");
    console.log("++-.-..:+o++:--:::://os/---:-..-:/++//sooso++++o+so///o+:dhmohmyo+o/y+o``/+oos/:/+o+.-::/:-.`:...`.-.....-/++/:::----:-:-:/y+---..:/+s++++///-:+/+o+/:");
    console.log(":/:.```-/+++::::////+ys/.---....::/-:/syyys++++++o+o+/oo.hhd+/hdosy+hos..+ooss+/osso+/.--/.`.-`.`-:--:---:/+--::-.`--::/::/y/.-...-++ysoo+::--:++++::-");
    console.log("-/:.```./o+//:--////+yo:-:---:..-::-:+ssyyysso///++so++y::hNyoddhhymds:`/so/++:+oso////-``.....`.-----/::/+:-:/-...-:-:://s/:--..-:/+yso+::-.:::/+//-.");
    console.log("--:--..-+o++/::/++//oh+:.--::--:-//://+syyhhhyooossso+++s/+dhsdmd:yhd/`:ssooo+:ooo+/:/:-::.``` `-:::---:/+///+:-.`..---:/oo-:-..-:/:/sso:.--:://++:/:-");
    console.log("-.-:-:-/o+++++/+oooosho//::/-.-:-:/++++oyyhhyysoooooso+++ss+yyhddyds+-+s++/s+::/+o//::--:/:-```..::--:-:++::/+:--.-::-.-/s/--::.:++++s+:.--:///os/:--/");
    console.log("-:/+:::+s++++++///+oyho:.:::-...-/ooossossyhyyys+++sss++++oyshs+sssooo+:::./:-/+o+::/::///:::-.--:---::+s/--:+:---++++::/o..-:..:////so:-:-/+::+///+oo");
    console.log("/+o//:+oso+++o++/:oosh+:://:-.--:+oosssosshhhhyys+/++/+oo/+ooNNyhNh//+:-+/+/:-+/+///:--:+///+/:::/:.-:+o/:-::::---/o+o+:oo--:/...:::/yo:::-:::/+---+y/");
    console.log("-////:/+///::/:/++++sho////-...-:osooo+/syyysysoo+:///oo///+yNNsdNs://-.////::///::+/::+++/+++/--:--/ooo+-:++/::////++ooyo::+o://o++oss///ss+oyo/:-os:");
  },8000);
}

