function whitley () {
  console.log("Are you ready to see a portrait of the greatest country singer of all time?");
  setTimeout(function() {console.log("He's no stranger to the rain, ladies and gentlement, introducing...");}, 2000);
  setTimeout(function() {console.log("KEITH WHITLEY!");}, 4000);
  setTimeout(function() {console.log("ps. Better put your dev tools on full screen or bottom view");}, 6000);

  setTimeout(function(){
    console.log("NNmmmNNNNNNNNmNNNNNmNNmmmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mNmmmmNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmmmmmmmNNNmmmmmmmNmNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmmmmmmmmNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh");
    console.log("mmmmmNNNNNNNNNNNNNNNNNNMMMNNMMMMNMNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd");
    console.log("mmmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMMMMMNNMNNmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd");
    console.log("NNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmddddddmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd");
    console.log("NNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmmmmmmmmmmddhhhdmmmddmNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd");
    console.log("NNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNmmmmmmmhhhddddddddddddddmmmmmmmdhhhhhhhhmmmNNNNNNNmdmNMMMMMMMMMMMMMMMMMMMMMMMMd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNmmddhhddsyhyhhhhsosyhhhhhhhddmdddhhdmmmdhhyyhdhhhhdNNNmmmNNNNNNNNNNNNNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdmdddyysyhhyysooysysoossshhhhyyddmdyyhhhhhyysssyhhyyssshmNNNmmmmmNNNNNNNNNNNNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmhddhyhsshhhsooossohdhhsossyhhhysyhdhhhhhyyyssyysyhdhysssoshmNNNmmmmNNNNNNNNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdddydyyhysydhhysoyy+dmmdhddyyhddhssyyhddddhhhyyhddyydddhhyysyyhdmNNNmmNNNNNNNNNmNNNNNNNNd");
    console.log("MMMMNMMMMMMMMMMMMMMMMMMMMMMNNNddhhsyssysyhhhhysoyyydmmNmhsshdmmddmdmmmmmdddhyyhdddmddhddddhhsoyhhmmNNNNNNNNNNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMNNNmdhdhhssyosyyyhyyyysyhdymmmmdyhhmmmmmmddmdddhyyyo+shddmmdddmddddyssydhdmNNNNmNNNNNNNNNNNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMNNNmdhyyhhhhyhhyyyysshhddhmmdmmNmmmdmNNNNmmmmmdhddhddhhhhdmddmdmddhhdhyyshdddmNNNmNNNNNNNNNNNNNNh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMNmmddhhyyyhhmddhhhyssyhmmmmmNNdmNmNNNNNNNNNNmmmmdmNmmmdyyyhyhddddhdhddmhs++sssydmNNNNNMMMMMMMNMNNd");
    console.log("MMMMMMMMMMMMMMMMMMMMMNmhhhhyyhyyhyhhhyhdyoohNmmNNNNNNmNNNNMMNNNNNmmmmNmhddhyyhhhyhdddddhhhddddhs++oyyhmmmmmmNMMMMMMMMMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMNhhhydyyyyyhyyyshyyshs+smNNNNNNMNNNMMNMNNNNNmmmdhddhyssssyyyyyyhhddddhmmddhysoshddddddddmNMMMMMMMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMmhddddoyhyysssssohdosdysdmmmNNMMMNNMMMMNNNNNNNNmhyss+/+hhhhyyoooyhdmmmmmhhhhhhyyhddddddmdmNNMMMMMMMm");
    console.log("MMMMMMMMMMMMMMMMMMMMmhdmhhyossoosyssoshddddhssyyhdNMMMNMMMMNNmmNNNNmhhs/o+ohhhddddhdhhmmNNNmydddhhhhyydhddddmddmmmmNNNNd");
    console.log("MMMMMMMMMMMMMMMMMMMNNddhysssoososssssoydmmsymNNNNNNMMMNNNNNNNNNNmdyyssooo+oyhdmmmNmmmdhdhddhhhhhyyydhhyhhddhddhhdmdmmmdy");
    console.log("MMMMMMMMMMMMMMMMMMNmmmdyyyssyssyyyyyhhysys+dNNNNNNNNNmNNmmmNNNNmdddddhyyyossyhdhhdddmdhyssyhysyhysysssshyyhhhdddhddddddy");
    console.log("MMMMMMMMMMMMMMMMMMNddddhdhyoshddmddhhyyyhyymmmNNmNmdhhdddmNNNmNmNNNNmdmmyoyyyhhhhhhhhyyosyysyyyyysyso+syyyhdddmmddhddddy");
    console.log("MMMMMMMMMMMMMMMMMMmddddhhhyysyhdhhyhhyshdddddmmmdhsyysyhddmmNmdddhddmmdmyshssyyyhhhyhyssos++shhhyyhyooyyooyhdmmmmdyddddy");
    console.log("MMMMMMMMMMMMMMMMMMmhdhhhhhyyyyyyyhhho+oshddddmdyo++ys++syddhyo+ssssyhhhddydyssssoosyyssoo++oossyyyso+oysoosysddmmmhhddhy");
    console.log("MMMMMMMMMMMMMMMMMMNhhdyyhyysssssyyss///sydddhh+:/++s//+osys++/+o+y+syssyhyosyso+o+++ooooo++++++oo+/ooooosoosyhmmNdmdddhy");
    console.log("MMMMMMMMMMMMMMMMMNNdyyyyyhyoo+osso+oo+/syydds-::+sosoooossooyyyooy/ss/+oyo+oyo/oo+oooo+/:///:+++o/:+/+osyo/:hmNNNmmmdhhy");
    console.log("MMMMMMMMMMMMMMMMMNNmdhyyhysssyyyso/+yysoyddy:/o/syyyysooysoshhhyss+oso+ooo/ss+////+/++///-:+//osy++:/osyyso/ymmNNNNNddhy");
    console.log("MMMMMMMMMMMMMMMMNmNmmdyyhhysyhhyssyhhddyhhmh+yysyyyyysssssssyhyysso+oss+++/++++/://:-/::/+++oosys/s//+oyyssosyhmNNmmddhs");
    console.log("MMMMMMMMMMMMMMMNdmmmddyhddhysoossyyhhhhhddmhyhhhyysso/-:/ossssooo/:////////:::/:-://::/+oooossso/++:::osssyyysshmNdddhhs");
    console.log("MMMMMMMMMMMMMMMmhhdmdyyyhhdysoosssoo+ososhddddds//+o+-..:/+o+/----....---:::::///:/+/+/ooso++soooo+///+ossyssyyyhNddhddy");
    console.log("MMMMMMMMMMMMMMNmdhddhdhhhhmyssyss++///::/++syhs+-/+++/:-.----...`````....--://+os+//+++osysoo+++++/++//syyhyyyyyydmmdhhy");
    console.log("MMMMMMMMMMMMMMMmdhsyhdhhmNNmhyyso///::-----:/o+/:-://+/:-.-.``.-..```.--..-:/++/+/:/++o+osoo//:::/::--/oyhhyyooyhhmmhyys");
    console.log("MMMMMMMMMMMMMMMdmdo+hdmdhmNNmhso+/:::----..-.--...-:-:--..``  `--.```.---..:::::-:::++oooso+///++////:/sdmmhhyosyhhmhhhy");
    console.log("MMMMMMMMMMMMMMNmmdyhddddydMNdso+//::-----................````  ``.````..-:------:/:/+/++ooooo//oso/+oo+yddddhyssyhhhdhhs");
    console.log("MMMMMMMMMMMMMMMNNhhmdydmNMMNmyoo+/:::---......`....`````       ````.``..----.--:://::++oo+++o/osso:-:ossydmmmdyyoyhdyyss");
    console.log("MMMMMMMMMMMMMMMMNmmmdddNMMMNNmdhyhs++/:---........```           `````........---:://://oso:/+oshhso++sosydmmdmhyyyhsooyy");
    console.log("MMMMMMMMMMMMMMMMNNmmhhmNNMMNdyyyyyhyyyyo/:.....-....````       ````..........---:://///oys///++shsooshyyhhyhdddhdddyyyhy");
    console.log("MMMMMMMMMMMMMMMMNNmmddmNNMMNmddhddddssydy+:-----:.-/ooo+//:-------..........--.-::/::-:ssyo+/++oss://+oyhysshdmdhhhmhhhy");
    console.log("MMMMMMMMMMMMMMMMNmmmmdmNNMMmmmhymmMmo..:oy+----::--++syhhhhsooo////:--..--------::///::osyo::/+oo+/:-:oyho+ssyyssyhmdhhy");
    console.log("MMMMMMMMMMMMMMMMNmmmNmdmdmNhhdo++yy+``./.:s:.```.-----://ooo/:::////:------:----://+/+:+oyy+:/osyso++ohhooo+soysshhmmhhy");
    console.log("MMMMMMMMMMMMMMMMMNmNmmddNNmsohs++/::----.:s:.```.....--://hNNds:-.----::/:----:-::/+/++++yhyo+/+oso+ssdmhoo++++syhdmmhhy");
    console.log("MMMMMMMMMMMMMMMMMMMNmNNNMMh+osso//::::--:oo-.``.-..```.:/.smNdo-+o/:-------:----:://+osyyyhhs++ooysoosddhoso+ooydddhhhhy");
    console.log("MMMMMMMMMMMMMMMMMMNmmddmMNy+//oo+++//::/os:.``..-.```.::::-/:. `.::----...-------:/:/syyyhddyooyyhhy+sddy/yhhdddddyhhhhy");
    console.log("MMMMMMMMMMMMMMMMMMmmmhdNMNs+//////:::::oy+-.`..--.````-:::-.`  ```..........-----://+shhhyyyysshdddysohdhydmmddyyddmmmmd");
    console.log("MMMMMMMMMMMMMMMMMNdmdhmNMms+/::::::::/+yo-.`..--..`  ``.---.```````...````..----::/oyyhddysosyshmmdsooydhddhdhdhhdhdmNNm");
    console.log("MMMMMMMMMMMMMMMMMNdyyhmMMms+/:::::/::+so:.`.......```````......``````````..--:::::/oohddhs/:ossyhddhyyyhssosyshdmhyhNMMN");
    console.log("MMMMMMMMMMMMMMMMMMNNmmNMMNho+/:::::/oss/-.`..-...```````````..``.```````.-:-::::/:+ssyyhs/-:/--/osddhhyyyyyshdyhmmddNMMN");
    console.log("MMMMMMMMMMMMMMMMMMMNNNNNMMms+/::://sss+:-``.---.....--.`````````  `````..--:::////osyyys/--//::::shyyyyyyhdhysyddddmMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMNNNNNMMNho/////+hys/:.``.-------:::::.```      ```...---://///osyssyo:.-.``.-/yhyhddhyddhysyhhshmMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMNNNMMMNds////+ohmo/:. `------:::.`.-/:..`     `...----:://///ssssyho---```.--odddddmmmdddhhhhhhmMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMNNmMMMNdh+osyyydmds/:-://////:-......//:-.```...------::///++yhyhdyh:..``.-:shmddmmmmmmmddddhhdmMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNNMNNdhyyddhdddhdyssoshysyyo+++/-...:+:--..-----:::--:/++osshhddydho//+shdmmdhhdmNNdhddhhyydmNMMMN");
    console.log("MMMMMMMMMMMMMMMMMMMMNNNMMMMmdhyysyydmmmmhs/sdddhhyshyso+/---//:--:::::::::///oshhdddmdymNNmNNNNNNNmdyydmdssyhddddhdmNNNm");
    console.log("MMMMMMMMMMMMMMMMMMMMNNNNMMMmmho/::+yddo/+/:/syhyssyhyssoooo+:/:--:///:::::/++sdhdhddmddNNNMMMNhyddmdhhmmdhhdhdddmdddmddh");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNNMMNNNds+::oyhhy/.  ````.``--/osssysyo/---:/+::/+/++oosdddmmNmddmNNMMNmdyoydhyhmmmdhdhhyhhhddhddh");
    console.log("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/ohysoo+/-:.`.--://+o+//syhs+--//+++//syyyshhdmNNNNNmmmNMMMNdyo/+syhdNNddyhhhhhhhhhyddh");
    console.log("MMMMMMMMMMMMMMMMMMMMMNNMMMMMMNmdy++sso++++++////:::---...:osy+-:+osssssshhhdhdmmNNNNmmNmNNMNNNNdyosyddNmmddhyyhddddhhdmm");
    console.log("MMMMMMMMMMMMMMMMMMMMMNmNMMMMMNmdys+ossosso++//--.........-++oo++ssyyyyyyyddmmmmNNNNmmNNMNNNNNhddyoohdymmdmmdhddddddhddmd");
    console.log("MMMMMMMMMMMMMMMMMMNNmmddNMMMMMNmhhs+syyddyyyyoo/::--....-:/osyyyhhhyyydmmmmNNNNMNNddmNMNNmmmNmsoyyhhyyhhdhyhdddhhhsyhyyh");
    console.log("MMMMMMMMMNNNmmmddhyyyhyydMMMMMNmmdyo/syyhddhhyys+/--.--::osyhdmmdddhdmmNNNNNNMMNmhyhdNNNddhdmmdssyhhhyyyhddddhddhysssosy");
    console.log("MMMMMNmhyyyhyysss+o/+o/symMMMMNNmmdyoosyyhhhys++/:---::/oyhdmmNNNNNNNNNMMMMMMNmhhyyyydmdyyyhddddddddhhyyyhhddyyyso++o+++");
    console.log("MMNmhyssoosssyoo+:o/:/:+/sNMMMMNNNmmdhhyshyyy+:::://o+syhhdmNNNNMMMMMMMMMNNmdysoyyyssyhhsshdmNmmmmdhhhhhhddddyyyso//:::-");
    console.log("mhy++/sysossso/--:-.-:--+odMMMMNNNNmmdhyhyyso//+ssoyddddmmNNNMMMMMMMMMNNdyss++ooyhyhhyhoosmmNNNNNmmhyshhdmmmdhdh//o+/:--");
    console.log("o++/+-ss++o++--..-:::-::/+omMMMMMMNmmmdhhhhyssyddhhmmmmmNNNMMMMMMMMMNdhy++++++osshdmhysoshyydmmmmmmddddmmmmNmmds+/+/+///");
    console.log("/:////+/:+oo:-----//::/+o++odNMMMMMNNmdhmdddhdmmmmmmmmNNNMMMMMMNNmdys+++++++oossssoyhhhdhyydmdddmhhdddmdhyhdhso+///+///:");
    console.log(":/+:://::/++..--../++///+:/oshmNMMMMMNNNNNmmmmmNNNNNNMMMMMNNmdyyso+++++++oossosso:/sohdyssdddsshhssyyyyyysyh+++://://://");
    console.log("-::.--/::/+/.--...///:-://oo++syhhdmNNNMMNNNMMMNMNNNNNmmdhyso++++++++++oossoso+///ooooso/sdhyhhhyssoo/+//oyy//-/-::-.://");
    console.log(".---.-///+/:--..`.-/+:///ooo+/++o+//sdmNmmmmmNNNdhyyssoo+++++++++++++oosssooo-`-/os/:/--:+o/-+s+/+//:-//oyo/--.::+/::/+/");
    console.log(".-:::::///-.....`.-//:/++sso+++//:-/osydhhhhydhdddyoo+oooooooo+oo+oo++++oso/:--/s/-::-.`.::--+/::-..:///y+.-/:../+:+s/+/");
    console.log(".----:://--.--:-.-//:-/+osyoo+///-:+ssshyyyyyyhhdddhyysssssoooooooo+//++++:.::o+-:::```--/:://:-..--:-:/o-..:-.-::+/+so/");
    console.log("------:::-----:---/+::++osyo+//+:-/+syhyyyhyyosyhdddhhhyyssossyso+o+++/---.-///---:.`.-:::.:/-:...::::/o/-`./--://s+os+o");
    console.log(".::--::---.-----:-++:://oooo////:/+oyyyssyyssysosyhhysyyyyyyyoo////::::--::.:::::/:..::-...+///-.-:/::o:-..::-.-:://soo+");
    console.log("------:-.//:---..-o+:/+/++++///+/:+oo+ssoyhsooyhh+s+::-/ohss/:::::/:-:///-`..:s+/:--:-::-.++::...:://++...-+:-..--/+/++/");
    console.log("----::.-://::--:-:++/++::++///o+::+s/+oyysys+:ymNho::-`./dy:---`.++///-....--://+-:/:-:--/:---..:/-:/o....-+:-...-+/----");
    console.log("---.---:/+/:-----/o//+:-///:++o++/+//osoos+/+//ys+ooos/+ds+o/...:+++-..--:/:/-::--/:/-..//-:-.`.-/--//````:o....-//:...:");
    console.log("-:-.--:/+//-----:/o//+:-://+o+o+o/+:o+o+/o+/++/sooo/oo/+.+o:+---::///.::-/+/+/:..:-:/--:/-:-``..-:--+...-/os::::/--:..:-");
    console.log("/+:...-/+/:::/://oo+/+:-://oooos+-/:://oss/-+:hdysssyh/o+.+/:--/-:::-.:+/-:+/-..-::--::/-::-.---/:-o:...:/yo::/o/--.:+/:");
    console.log("++-..-:/+/:-::::/so/::--::++o+y+://+/++os+::/sddsms+oo+/s -++++-/+:-:/:/+.-//-.:---..-/+:::.--:/:-/s-..-:/s+:/++/::/+o/:");
    console.log("//..../++/-:////+y/.---..-:///+yys+/+++o+//o++hh+hd++ooso -oos+/+os/:-::-`-`.`------://::/..-:::::s+--..:/so+o/::-+/++:-");
    console.log(":/-```:++//--//:oy/-----..::-:ssyysso//+os++y.ymoydhhhds:.oo/+/+os+++:......`----::://--:-..--:///s:-..-:+syo/:--::/+/:-");
    console.log("-::-../o++/:/+++sy/--::---:///+syyhhsoosss++oo/hyhmd/yd+`ososo:ooo/:/:::.```.-::---/+//+:-...--:/s/:-.-:/:oyo---::/++::-");
    console.log("--/::-+++++++++oyy/:-/:.--:++oooyyhyyso++ss+++sssyshyy+/o++:+/-/+/:::::::-``..::-::+/::+:--:/:--+o-.:--/++oo---/+/+s+::+");
    console.log("/++/:/so+++++:+oyy:-//-.--/ooososyhhyyso++++o++oymhyms/+/-/:/-:+o/::::////+-:::--:+o:-:/---/oo+:o/.::`.:::os::::::+:::oo");
    console.log(":/+//++//:///+++sy//::-..:+sooo+syyyyso+://+o//+hNhdm+//--+//:/:/://::++/++/-::-/+o+-/+/:///++ooy/-/+:/+++os//+s+os/::s/");
  },8000);
}

